language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - yarn lint
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
