language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm

script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: deploy
    - name: "Deploy"
      script: yarn release
      on:
        branch: master
